name: tsperf
channels:
  - defaults
  - r
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.15.0
  - pandas=0.23.4
  - xlrd=1.1.0
  - urllib3=1.21.1
  - jupyter=1.0.0
  - r-essentials=3.5.1
  - r-bayesm=3.1_0.1
  - matplotlib=2.2.3
  - scikit-learn=0.20.3
  - pip:
    - csvtomd==0.3.0
 
