#!/bin/bash

# Run in TSperf base directory:
# source ./common/setup

ENVNAME="tsperf"

echo "Creating Conda environment tsperf"

conda env create -f common/conda_dependencies.yml

echo "Activating tsperf Conda environment"

source activate $ENVNAME