#!/bin/bash
c++ -DEIGEN_FAST_MATH -fPIC -funroll-loops -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -Ofast -g -march=native -O2 -g -DNDEBUG -I/home/deegup/dynet/dynet -I/home/deegup/dynet/eigen/eigen -I/home/deegup/dynet/dynet/build $1.cc slstm.cpp -o $1 -lodbc -rdynamic /home/deegup/dynet/dynet/build/dynet/libdynet.so -lpthread -lrt -Wl,-rpath,/home/deegup/dynet/dynet/build/dynet
